0.2.2: transfer errors output, updated readme

diff --git a/esupload b/esupload
--- a/esupload
+++ b/esupload
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-ver="0.2.1"
+ver="0.2.2"
 
 # defaults
 remote_user=$USER
@@ -77,6 +77,8 @@ if [ -d "$CFGDIR" ]; then
 					fi
 				elif [ "$line" == "res:0 0" ]; then
 					res=0	
+				else
+					echo "$line" 1>&2 # in case of error
 				fi
 			done < <((pv -n -i $track_interval "$loc" | ssh -q -i "$remote_ident" "$remote_user@$remote_host" "cat > '$rem' && chmod $chmod '$rem'"; echo "res:${PIPESTATUS[*]}") 2>&1)
 			# what's happening here:
@@ -84,7 +86,7 @@ if [ -d "$CFGDIR" ]; then
 			# after that we're also reading PIPESTATUS to check the result 
 		else
 			rem=$(printf %q "$rem")
-			rsync --chmod=$chmod -e "ssh -i \"$remote_ident\"" "$loc" "$remote_user@$remote_host:$rem" > /dev/null 2>&1
+			rsync -q --chmod=$chmod -e "ssh -i \"$remote_ident\"" "$loc" "$remote_user@$remote_host:$rem" > /dev/null
 			res=$?
 		fi
 		if [ $res -ne 0 ]; then
